import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en">
        <body className={`${inter.className} flex flex-col`}>
          <div className="flex flex-wrap">
            <Sidebar />
            <div className="flex-grow p-12 pt-5 gap-4"> 
            {children}
            </div>
            
          </div>
        </body>
      </html>
    </SessionProvider>
  );
}
